sudo: required

language : 
  - go  
os:
  - linux
services:
  - docker

# branches:
#   only:
#     - master
#     - /^v\d+\.\d+\.\d+(\.\d+)?(-\S*)?$/
    
cache:
  bundler: false
  directories:
  - .build-cache          # images.txt
# Handle git submodules yourself
git:
    submodules: false
# Do a github login using token
before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
  - pip install --user awscli
install:
  - go get -u github.com/constabulary/gb/...
  - go get -u github.com/tools/godep/...
  - go get -u github.com/ains/go-test-html 

jobs:
  include:
    - stage: perf-test
      script:
        - mkdir -p $GOPATH/src/github.com/TIBCOSoftware
        - cd $GOPATH/src/github.com/TIBCOSoftware
        - git clone https://github.com/TIBCOSoftware/mashling.git
        - git clone https://github.com/TIBCOSoftware/mashling-recipes.git
        - git clone https://github.com/TIBCOSoftware/mashling-cicd.git mashling-cicd
        - cp -r $GOPATH/src/github.com/TIBCOSoftware/mashling-cicd/dependency-config/* $GOPATH/src/github.com/TIBCOSoftware/mashling
        - cd mashling
        - ls
        - godep restore
        - make
        - cd $GOPATH/src/github.com/LakshmiMekala/testrep
        - chmod ugo+x ./build.sh
        - ./build.sh
    #     - if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then
    #       mkdir -p $GOPATH/src/github.com/TIBCOSoftware;
    #       cd $GOPATH/src/github.com/TIBCOSoftware;
    #       git clone https://github.com/TIBCOSoftware/mashling.git;
    #       git clone https://github.com/TIBCOSoftware/mashling-recipes.git;
    #       git clone https://github.com/TIBCOSoftware/mashling-cicd.git mashling-cicd;
    #       cp -r $GOPATH/src/github.com/TIBCOSoftware/mashling-cicd/dependency-config/* $GOPATH/src/github.com/TIBCOSoftware/mashling;
    #       cd mashling;
    #       godep restore;
    #       make all;
    #       cd $GOPATH/src/github.com/LakshmiMekala/testrep;
    #       chmod ugo+x ./build.sh;
    #       ./build.sh;
    #       fi
    # - stage: build
    #   script:
    #     - if [[ "$TRAVIS_EVENT_TYPE" != "cron" ]]; then
    #       mkdir -p $GOPATH/src/github.com/TIBCOSoftware
    #       cd $GOPATH/src/github.com/TIBCOSoftware
    #       git clone https://github.com/TIBCOSoftware/mashling.git
    #       git clone https://github.com/TIBCOSoftware/mashling-cicd.git mashling-cicd
    #       cp -r $GOPATH/src/github.com/TIBCOSoftware/mashling-cicd/dependency-config/* $GOPATH/src/github.com/TIBCOSoftware/mashling
    #       cd mashling
    #       godep restore
    #       go test ./... -v 2> >(tee gotest_stderr_file) | tee gotest_stdout_file
    #       go install ./...
    #       make all
    #       mashling help
    #       cd $GOPATH/src/github.com/TIBCOSoftware
    #       cd mashling-cicd/sample-recipes
    #       rm -rf builds
    #       mkdir -p builds/latest
    #       chmod ugo+x ./build-recipes.sh ./sanity.sh ./gotestreport.sh
    #       ./gotestreport.sh
    #       ./build-recipes.sh
    #       ./sanity.sh
    #       cd $GOPATH/src/github.com/TIBCOSoftware/mashling-cicd/docker/mashling;
    #       chmod ugo+x ./build-mashling.sh ;
    #       ./build-mashling.sh ;
    #       fi
    #   after_success:
    #     - if [ "$TRAVIS_EVENT_TYPE" != "cron" ]; then 
    #       "docker login -u=\"${DOCKER_USERNAME}\" -p=\"${DOCKER_PASSWORD}\" tibdocker.tibco.com"
    #       source $GOPATH/src/github.com/TIBCOSoftware/mashling-cicd/scripts/init.sh
    #       mashling::module::postbuild mashling mashling
    #       fi
after_script:
  - "[ -f \"${HOME}/.netrc\" ] && rm -f ${HOME}/.netrc"
  - "[ -f \"${HOME}/.aws\" ] && rm -f ${HOME}/.aws"      