sudo: required
language : 
  - go
before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
install:
 - mkdir -p $GOPATH/src/github.com/TIBCOSoftware
 - sudo apt-get install zookeeperd
 - sudo pip install kafka-python
 - sudo apt-get install libxml2-utils
 - sudo apt-get update -q
 - sudo apt-get install python-pip python-matplotlib
 - sudo pip install -U multi-mechanize
  
script:
  - mkdir -p $GOPATH/src/github.com/TIBCOSoftware
  - cd $GOPATH/src/github.com/TIBCOSoftware
  - git clone https://github.com/TIBCOSoftware/mashling-recipes.git
  - cd $GOPATH
  - wget http://www-eu.apache.org/dist/kafka/1.0.0/kafka_2.11-1.0.0.tgz -O $GOPATH/kafka.tgz > /tmp/kafka.log
  - mkdir -p $GOPATH/kafka && cd $GOPATH/kafka
  - tar -xvzf $GOPATH/kafka.tgz --strip 1 > /tmp/kafka.log
  - cd ..
  - git clone -b kafka-test https://github.com/LakshmiMekala/testrep.git 
  - cd testrep
  - chmod ugo+x ./kafka-run.sh
  - source ./kafka-run.sh
  #- source ./linux.sh
  - testcase1
  - testcase2
