sudo: required
language : 
  - go  
os:
  - linux
services:
  - docker    
cache:
  bundler: false
  directories:
  - .build-cache          # images.txt
# Handle git submodules yourself
git:
    submodules: false
# Do a github login using token
before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
  - pip install --user awscli
install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/constabulary/gb/...
  - go get -u github.com/ains/go-test-html 
  
script:
  - go get -u github.com/TIBCOSoftware/mashling/...
  - cd $GOPATH/src/github.com/TIBCOSoftware
  - git clone -b feature-dep-update https://github.com/TIBCOSoftware/mashling-cicd.git mashling-cicd
  - cd mashling
  - git branch -a
  - git checkout feature-dep
  - dep ensure
  - make all
  # - go test ./... -v 2> >(tee gotest_stderr_file) | tee gotest_stdout_file
  # - make all
  - mashling help
  - cd $GOPATH/src/github.com/LakshmiMekala/testrep
  - lscpu
  - mkdir -p $HOME/builds/latest
  - chmod ugo+x ./build-recipes.sh
  # - ./gotestreport.sh
  - ./build-recipes.sh