language : 
  - go  
before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
 
os: 
  - linux
#  - osx
#  - windows

  

script:
   - chmod ugo+x ./build.sh 
   - ./build.sh

after_script:
  - "[ -f \"${HOME}/.netrc\" ] && rm -f ${HOME}/.netrc" 


