sudo: required

services:
  - docker
cache:
  bundler: false
  directories:
  - .build-cache          # images.txt  
language : 
  - go  
before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
  -  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
#    fi
 
os: 
  - linux
  - osx
  - windows

install:
  - go get -u github.com/constabulary/gb/...
#  - travis_wait 30

script:
   - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    fi
   #- chmod ugo+x ./build.sh 
   #- ./build.sh

after_script:
  - "[ -f \"${HOME}/.netrc\" ] && rm -f ${HOME}/.netrc" 


