sudo: required
language : 
  - go
before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
install:
#  - go install ./...
  - sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa --yes
  - sudo apt-get update -q
  - sudo apt-get install mosquitto
  - sudo apt-get install libmosquitto-dev
  - sudo apt-get install mosquitto-clients
  
script:
  - mosquitto
  - mosquitto_sub
  - mosquitto_pub
  - mosquitto_pub -m "123" -t "abc" & mosquitto_sub -t "abc"
