sudo: required
language : 
  - go
before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
install:
#  - go install ./...
  - sudo apt-get install zookeeperd
  - sudo apt-get update -q
  
script:
  - mkdir -p $GOPATH/src/github.com/TIBCOSoftware
  - cd $GOPATH
  - wget http://www-eu.apache.org/dist/kafka/1.0.0/kafka_2.11-1.0.0.tgz -O $GOPATH/kafka.tgz > /tmp/kafka.log
  - mkdir -p $GOPATH/kafka && cd $GOPATH/kafka
  - tar -xvzf $GOPATH/kafka.tgz --strip 1 > /tmp/kafka.log
  - cd ..
  - git clone -b kafka-test https://github.com/LakshmiMekala/testrep.git 
  - cd testrep
  - chmod ugo+x ./linux.sh
  - ./linux.sh
  #- source ./linux.sh
#  - testcase1
