language : 
  - go  
before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
 
os: 
  - linux
  - osx

install:
  - go get github.com/constabulary/gb/...
  - go get -u github.com/constabulary/gb/...
  - go get -u github.com/TIBCOSoftware/flogo-cli/...
  - go get github.com/TIBCOSoftware/mashling-cli/...
  - go get -u github.com/TIBCOSoftware/mashling-cli/...
  - pwd
  - cd ..
  - git clone https://github.com/LakshmiMekala/sample-recipes.git
  - cd sample-recipes
script:
   - chmod ugo+x ./build.sh 
   - ./build.sh

after_script:
  - "[ -f \"${HOME}/.netrc\" ] && rm -f ${HOME}/.netrc" 

after_success:
   - chmod ugo+x ./push.sh
   - ./push.sh
